ccflags-y += -Idrivers/media/platform/msm/camera_v2-lenovo
ccflags-y += -Idrivers/media/platform/msm/camera_v2-lenovo/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2-lenovo/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-lenovo/common
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
