ccflags-y += -Idrivers/media/platform/msm/camera_v2-lenovo
ccflags-y += -Idrivers/media/platform/msm/camera_v2-lenovo/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-lenovo/sensor/io
obj-$(CONFIG_MSM_CCI) += msm_cci.o
