ccflags-y += -Idrivers/media/platform/msm/camera_v2-lenovo
ccflags-y += -Idrivers/media/platform/msm/camera_v2-lenovo/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-lenovo/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-lenovo/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
