ccflags-y += -Idrivers/media/platform/msm/camera_v2-lenovo/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2-lenovo
ccflags-y += -Idrivers/media/platform/msm/camera_v2-lenovo/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-lenovo/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_flash.o
